- name: Auto-configure Zookeeper
  become: yes
  block:

    - name: Copy auto-configure script
      ansible.builtin.copy:
        src: auto-configure-zookeeper.py
        dest: /opt/zookeeper/bin/
        owner: zk
        group: zk
        mode: '0755'

    - name: Copy auto-configure systemd unit file
      ansible.builtin.copy:
        src: auto-configure-zookeeper.service
        dest: /etc/systemd/system/auto-configure-zookeeper.service

    - name: Systemd to re-read config
      ansible.builtin.systemd:
        daemon_reload: yes
        name: auto-configure-zookeeper
        enabled: yes
