- name: Auto-configure Zookeeper
  block:

    - name: Copy auto-configure script
      become: zk
      ansible.builtin.copy:
        src: auto-configure-zookeeper.py
        dest: /opt/zookeeper/bin
        owner: zk
        group: zk
        mode: '0755'

    - name: Copy auto-configure systemd unit file
      become: yes
      ansible.builtin.copy:
        src: auto-configure-zookeeper.service
        dest: /etc/systemd/system/auto-configure-zookeeper.service

    - name: Systemd to re-read config
      become: yes
      ansible.builtin.systemd:
        daemon_reload: yes
