---
- become: yes
  block:
    - name: Copy the template config
      ansible.builtin.copy:
        src: elasticsearch.yml.j2
        dest: /opt/elasticsearch/config/elasticsearch.yml.j2
        mode: '0644'

    - name: Increase maximum number of memory map areas that a process can use
      become: yes
      sysctl:
        name: vm.max_map_count
        value: 262144

    - name: Copy auto-configure script
      ansible.builtin.copy:
        src: auto-configure-elasticsearch.py
        dest: /usr/local/bin
        mode: '0755'

    - name: Copy auto-configure systemd unit file
      ansible.builtin.copy:
        src: auto-configure-elasticsearch.service
        dest: /etc/systemd/system/auto-configure-elasticsearch.service

    - name: Systemd to re-read config
      ansible.builtin.systemd:
        daemon_reload: yes
        name: auto-configure-elasticsearch
        enabled: yes
