---
- name: Build Kafka AMI
  hosts: default

  tasks:
    - name: Install openjdk-8-jre
      become: true
      apt:
        name: openjdk-8-jre-headless
        state: present
        update_cache: yes

    - name: Get java version
      ansible.builtin.command:
        cmd: java -version
      register: java_version

    - name: Show java version
      debug:
        msg: "{{ java_version.stderr }}"
