# This is a basic workflow to help you get started with Actions

name: Build AMI

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      token_code:
        description: MFA token
        required: true

env:
  AWS_SHARED_CREDENTIALS_FILE: aws-credentials

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mfa:
    name: Authenticate to AWS through MFA

    runs-on: ubuntu-18.04

    container:
      image: docker://goodman25/test-image:latest

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - uses: actions/checkout@v2

      - name: Authenticate through MFA
        run: scripts/aws-mfa.py --duration 1800 --credentials-path ./aws-credentials github-actions ${{github.event.inputs.token_code}}

      - name: Remember credentials
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.run_id}}
          path: aws-credentials
          retention-days: 1

      - name: Peek identity
        run: python3 -c 'import json; import boto3; print(json.dumps(boto3.client("sts").get_caller_identity()))' | python3 -m json.tool

  validate:
    name: Validate Packer

    needs:
      - mfa

    runs-on: ubuntu-18.04

    container:
      image: docker://goodman25/test-image:latest

    strategy:
      matrix:
        service:
          - kafka
          - zookeeper

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: ${{github.run_id}}

      - name: Validate Packer file for ${{matrix.service}}
        run: packer validate -var 'service=${{matrix.service}}' packer/image.pkr.hcl

  build:
    name: Build AMI

    needs:
      validate

    runs-on: ubuntu-18.04

    container:
      image: docker://goodman25/test-image:latest

    strategy:
      matrix:
        service:
          - kafka
          - zookeeper

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: ${{github.run_id}}

      - name: Build AMI for ${{matrix.service}}
        run: packer build -var 'service=${{matrix.service}}' packer/image.pkr.hcl
