# This is a basic workflow to help you get started with Actions

name: Build AMI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - packer/**
  pull_request:
    branches:
      - master
    paths:
      - packer/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build AMI:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        service:
          - kafka
          - zookeeper

    steps:
      - name: Validate Packer file for ${matrix.service}
        uses: docker://goodman25/test-image:latest
        run: packer validate -var 'service=${matrix.service}' packer/image.pkr.hcl

      - name: Bake AMI for ${matrix.service}
        uses: docker://goodman25/test-image:latest
        run: packer build -var 'service=${matrix.service}' packer/image.pkr.hcl

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
